
version: '2'
services:
  client:
    build:
      context: client/
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
  server:
    build:
      context: server/
    volumes:
      - ./server/:/app
    ports:
      - "8888:8888"